<?php

/**
 * @file
 * Contains example_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function example_entity_theme() {
  $theme = [];
  $theme['organisation'] = array(
    'render element' => 'elements',
    'file' => 'organisation.page.inc',
    'template' => 'organisation',
  );
  $theme['organisation_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'organisation.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function example_entity_theme_suggestions_organisation(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#organisation'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'organisation__' . $sanitized_view_mode;
  $suggestions[] = 'organisation__' . $entity->bundle();
  $suggestions[] = 'organisation__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'organisation__' . $entity->id();
  $suggestions[] = 'organisation__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
