definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  entity__comment_type__collection:
    enabled: false
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    weight: 0
  entity__organisation_type__collection:
    weight: -58
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__organisation__collection:
    weight: -58
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
